{% set version = "0.1.3" %}

package:
  name: pykml
  version: {{ version }}

source:
  fn: pykml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pykml/pykml-{{ version }}.tar.gz
  sha256: e1a133e582f0b4652a6b00bac970b446d90580664e5a634a670731c990ff9f05

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - lxml >=2.2.6

test:
  imports:
    - pykml

about:
  home: http://pypi.python.org/pypi/pykml
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Python KML library.'

extra:
  recipe-maintainers:
    - ocefpaf
