{% set version = "0.2.0" %}

package:
  name: pykml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pykml/pykml-{{ version }}.tar.gz
  sha256: 44a1892e7c2a649c8ae9f8e2899ff76cae79ec6749ffb64d11140b4e87d0f957

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - lxml >=3.3.6

test:
  imports:
    - pykml

about:
  home: http://pypi.io/pypi/pykml
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Python KML library'

extra:
  recipe-maintainers:
    - ocefpaf
    - tylere
